useTabs: true
arrowParens: "avoid"
semi: true
singleQuote: true
printWidth: 80
trailingComma: "all"
plugins: ["prettier-plugin-svelte"]
pluginSearchDirs: ["."]
overrides: [{ files: "*.svelte", options: { "parser": "svelte" } }]
svelteAllowShorthand: true
svelteIndentScriptAndStyle: false
