name: Build

env:
  IS_MAIN: github.ref == 'refs/heads/main'
  IS_MAJOR: startsWith(github.event.head_commit.message, 'feat!:') || contains(github.event.head_commit.message, 'BREAKING_CHANGE')
  IS_MINOR: startsWith('feat:', github.event.head_commit.message)

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-latest
            arch: x86_64
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            arch: aarch64
            rust_target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          profile: minimal
          toolchain: stable
          target: ${{ matrix.config.rust_target }}

      - name: get rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.config.rust_target }}

      - name: setup node and install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: get yarn cache
        uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install uncached dependencies
        run: yarn install

      - name: build app
        uses: JonasKruckenberg/tauri-build@v1
        id: tauri_build
        with:
          target: ${{ matrix.config.rust_target }}
          args: --verbose

      # The `artifacts` output can now be used by a different action to upload the artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ matrix.config.arch }}
          path: "${{ join(fromJSON(steps.tauri_build.outputs.artifacts), '\n') }}"
