name: Create Executables

on: [push]

jobs:
  deploy:
    name: Compile Application
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin # additional target: github MacOS is x86_64

      - name: install app dependencies and test
        run: |
          npm install
          cd src-tauri && cargo test

      - name: build macos-intel
        run: npx tauri build --target x86_64-apple-darwin

      - name: build macos-m1
        run: npx tauri build --target aarch64-apple-darwin

      - name: Upload macos-intel
        uses: actions/upload-artifact@v3
        with:
          name: ttbl-mac_intel
          path: src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/**.dmg

      - name: Upload macos-m1
        uses: actions/upload-artifact@v3
        with:
          name: ttbl-mac_m1
          path: src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/**.dmg

  release:
    name: Check and upload to release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download macos-intel
        uses: actions/download-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ttbl-mac_intel

      - name: Download macos-m1
        uses: actions/download-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ttbl-mac_m1

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            \# Added
            \
            \# Changed
            \
            \# Fixed
            \
            Download the asset that matches your operating system below.
          files: |
            ttbl-mac_intel
            ttbl-mac_m1
