name: Create Executables

on: [push]

jobs:
  deploy:
    name: Compile Application
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin # additional target: github MacOS is x86_64

      - name: install app dependencies
        run: npm install

      - name: build macos-intel
        uses: tauri-apps/tauri-action@v0
        with:
          args: --target x86_64-apple-darwin

      - name: build macos-m1
        uses: tauri-apps/tauri-action@v0
        with:
          args: --target aarch64-apple-darwin

      - name: Upload macos-intel
        uses: actions/upload-artifact@v3
        with:
          name: ttbl-mac_intel
          path: src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/**.dmg

      - name: Upload macos-m1
        uses: actions/upload-artifact@v3
        with:
          name: ttbl-mac_m1
          path: src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/**.dmg
