name: Create Executables

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Compile Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Build App
        run: |
          make test
          make setup
          make update
          make
          mkdir dist/macos
          mv dist/ttbl.app dist/macos/ttbl.app

      - name: Upload MacOS
        uses: actions/upload-artifact@v3
        with:
          name: ttbl-mac_x64
          path: dist/macos

      - name: Upload Windows
        uses: actions/upload-artifact@v3
        with:
          name: ttbl-win_x64
          path: dist/ttbl/ttbl-win_x64.exe

      - name: Upload WebView2Loader.ddl
        uses: actions/upload-artifact@v3
        with:
          name: WebView2Loader.ddl
          path: dist/ttbl/WebView2Loader.dll

      - name: Upload ttbl-linux_arm64
        uses: actions/upload-artifact@v3
        with:
          name: ttbl-linux_arm64
          path: dist/ttbl/ttbl-linux_arm64

      - name: Upload ttbl-linux_armhf
        uses: actions/upload-artifact@v3
        with:
          name: ttbl-linux_armhf
          path: dist/ttbl/ttbl-linux_armhf

      - name: Upload ttbl-linux_x64
        uses: actions/upload-artifact@v3
        with:
          name: ttbl-linux_x64
          path: dist/ttbl/ttbl-linux_x64

      - name: Upload resources.neu
        uses: actions/upload-artifact@v3
        with:
          name: resources.neu
          path: dist/ttbl/resources.neu
