name: Create Executables

on: [push]

jobs:
  deploy:
    name: Compile Application
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup Environment
        run: make setup

      - name: Build macos-intel
        run: cargo-tauri build --target x86_64-apple-darwin

      - name: Build macos-m1
        run: cargo-tauri build --target aarch64-apple-darwin

      - name: Upload macos-intel
        uses: actions/upload-artifact@v3
        with:
          name: ttbl-mac_intel
          path: src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/**.dmg

      - name: Upload macos-m1
        uses: actions/upload-artifact@v3
        with:
          name: ttbl-mac_m1
          path: src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/**.dmg
