name: Lint Rust

on:
  push:
    paths:
      - 'src-tauri/src/**'
  pull_request:
    paths:
      - 'src-tauri/src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-rust:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: install webkit2gtk
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

        # uses: actions-rs/toolchain@v1
      - name: Install clippy with stable toolchain
        uses: caizixian/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - uses: gaoDean/clippy-check@v1
        env:
          CACHE_ON_FAILURE: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path=Cargo.toml --all-targets --all-features -- -D warnings
          name: clippy

      - uses: gaoDean/cargo@v1
        with:
          command: fmt
          args: --manifest-path=Cargo.toml --all -- --check
