name: Release binaries

on:
  push:
    tags:
      - v**

jobs:
  download:
    name: Download pre-built binaries
    steps:
      - uses: actions/checkout@v2

      - name: Download macos-intel
        uses: actions/download-artifact@v3
        with:
          name: ttbl-mac_intel

      - name: Download macos-m1
        uses: actions/download-artifact@v3
        with:
          name: ttbl-mac_m1

  upload:
    name: Upload binaries to new release
    needs: download
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "# Added\n\n# Changed\n\n # Fixed"
          files: |
            ttbl-mac_intel
            ttbl-mac_m1
